---
repos:
  # ✅ Markdownlint via lokal installiertem CLI (npx)
  - repo: local
    hooks:
      - id: markdownlint
        name: MarkdownLint (local)
        entry: npx markdownlint --config .markdownlint.yaml
        language: system
        types: [markdown]

  # ✅ cspell für deutsch/englisch, projektlokal konfiguriert
  # TODO: Deutsche konfiguration klappt nicht auf Anhieb...
  # - repo: https://github.com/errata-ai/vale
  #   rev: v3.12.0
  #   hooks:
  #     - id: vale
  #       files: \.md$


  # ✅ YAML-Linter (für GitHub Workflows & Templates)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
